In [27]:
import pandas as pd
import numpy as np
from skimpy import skim
from sklearn.preprocessing import MinMaxScaler

test = pd.read_csv('test.csv')
test_calendar = pd.read_csv('test_calendar.csv')
train = pd.read_csv('train.csv')
train_calendar = pd.read_csv('train_calendar.csv')

train = train.drop(['holiday_name', 'id'], axis=1)
test = test.drop(['holiday_name','id'], axis=1)

for col in train.columns:
    if train[col].dtype != 'int64':
        train[col] = pd.factorize(train[col])[0]

for col in test.columns:
    if test[col].dtype != 'int64':
        test[col] = pd.factorize(test[col])[0]

scaler = MinMaxScaler(feature_range=(1, 500))
scaler.fit(train)
train = pd.DataFrame(scaler.transform(train))

# for column in test:
#     print(test[column].value_counts())

from sklearn.model_selection import train_test_split
from sklearn import tree

#split data
# X_train,y_train = train.drop(['orders'], axis=1), train['orders']
# X_test,y_test = test.drop(['orders'], axis=1), test['orders']
X,y = train.drop([2], axis=1), train[2]
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.70)

#train data
trialData = {'numNodes':[],'mape':[]}

#add loop for features
#for k in range(3,34,3):
for i in range(2,15):
    #why is MSE inconsistent when start range from 5?
    #why is MSE very regular when start from 2?
    clf = tree.DecisionTreeRegressor(max_leaf_nodes = i)
    clf = clf.fit(X_train,y_train)
    #estimate quality of prediction
    prediction = clf.predict(X_test)

    #mean squared error (MSE) --> estimate accuracy
    error = 0
    for j in range(len(y_test)):
        error += abs((prediction[j] - y_test.iloc[j])/y_test.iloc[j])
    error = 100*(error/len(y_test))

    trialData['numNodes'].append(i)
    trialData['mape'].append(error)

trialData = pd.DataFrame(trialData)
display(trialData)

#display(train_calendar)
display(train)
display(test)
skim(test)

    numNodes        mape
0          2  105.560356
1          3  105.528942
2          4   86.669998
3          5   85.719602
4          6   84.319869
5          7   82.543222
6          8   79.757828
7          9   71.943793
8         10   72.650630
9         11   72.469077
10        12   72.589037
11        13   72.383581
12        14   71.880837

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1.0,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.646373,4.158228,1.000000,1.000000
1,1.0,1.418624,1.112768,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.646373,4.158228,1.440035,1.081191
2,1.0,1.837248,1.225537,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.646373,4.158228,1.880071,1.162382
3,1.0,2.255872,1.338305,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.292746,4.158228,2.320106,1.243573
4,1.0,2.674497,1.451073,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.939119,4.158228,2.760141,1.324764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7335,500.0,497.906879,174.437740,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,152.897668,4.158228,459.956790,499.675236
7336,500.0,498.325503,27.387797,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,258.256477,4.158228,494.719577,499.756427
7337,500.0,498.744128,499.774463,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,187.155440,4.158228,480.198413,499.837618
7338,500.0,499.162752,499.887232,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.646373,4.158228,431.794533,499.918809
7339,500.0,499.581376,500.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.646373,4.158228,473.157848,500.000000

,warehouse,date,holiday,shops_closed,winter_school_holidays,school_holidays
0,0,0,0,0,0,0
1,0,1,0,0,0,0
2,0,2,0,0,0,0
3,0,3,0,0,0,0
4,0,4,0,0,0,0
...,...,...,...,...,...,...
392,6,56,0,0,0,0
393,6,57,0,0,0,0
394,6,58,0,0,0,0
395,6,59,0,0,0,0
396,6,60,0,0,0,0

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 397    │ │ int32       │ 6     │                                                          │
│ │ Number of columns │ 6      │ └─────────────┴───────┘                                                          │
│ └───────────────────┴────────┘                                                                                  │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━━━┓  │
│ ┃ column_name               ┃ NA  ┃ NA %   ┃ mean      ┃ sd       ┃ p0  ┃ p25  ┃ p50  ┃ p75  ┃ p100 ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━━━┩  │
│ │ warehouse                 │   0 │      0 │     2.872 │     2.01 │   0 │    1 │    3 │    5 │    6 │ ▅▅▅▅▃▇ │  │
│ │ date                      │   0 │      0 │     30.08 │    17.61 │   0 │   15 │   30 │   45 │   60 │ ▇▇▇▇▇▇ │  │
│ │ holiday                   │   0 │      0 │   0.06801 │   0.2521 │   0 │    0 │    0 │    0 │    1 │ ▇    ▁ │  │
│ │ shops_closed              │   0 │      0 │   0.02015 │   0.1407 │   0 │    0 │    0 │    0 │    1 │   ▇    │  │
│ │ winter_school_holidays    │   0 │      0 │   0.02015 │   0.1407 │   0 │    0 │    0 │    0 │    1 │   ▇    │  │
│ │ school_holidays           │   0 │      0 │   0.07053 │   0.2564 │   0 │    0 │    0 │    0 │    1 │ ▇    ▁ │  │
│ └───────────────────────────┴─────┴────────┴───────────┴──────────┴─────┴──────┴──────┴──────┴──────┴────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯