In [25]:
import pandas as pd
import numpy as np
from skimpy import skim

test = pd.read_csv('test.csv')
test_calendar = pd.read_csv('test_calendar.csv')
train = pd.read_csv('train.csv')
train_calendar = pd.read_csv('train_calendar.csv')

train = train.drop(['holiday_name', 'id'], axis=1)
test = test.drop(['holiday_name','id'], axis=1)

for column in test:
    print(test[column].value_counts())

display(train_calendar)
display(train)
display(test)
skim(test)

warehouse
Prague_1       61
Brno_1         61
Prague_2       61
Prague_3       61
Budapest_1     57
Munich_1       48
Frankfurt_1    48
Name: count, dtype: int64
date
2024-03-16    7
2024-04-12    7
2024-04-16    7
2024-04-17    7
2024-04-18    7
             ..
2024-05-09    5
2024-03-31    4
2024-04-01    4
2024-05-01    4
2024-03-29    4
Name: count, Length: 61, dtype: int64
holiday
0    370
1     27
Name: count, dtype: int64
shops_closed
0    389
1      8
Name: count, dtype: int64
winter_school_holidays
0    389
1      8
Name: count, dtype: int64
school_holidays
0    369
1     28
Name: count, dtype: int64

             date holiday_name  holiday  ...  precipitation  snow   warehouse
0      2022-03-09          NaN        0  ...           0.00   0.0    Prague_1
1      2019-07-03          NaN        0  ...           0.00   0.0    Prague_1
2      2020-05-18          NaN        0  ...           0.00   0.0    Prague_1
3      2021-11-09          NaN        0  ...           0.00   0.0    Prague_1
4      2023-08-02          NaN        0  ...           2.50   0.0    Prague_1
...           ...          ...      ...  ...            ...   ...         ...
13302  2019-09-09          NaN        0  ...          14.20   0.0  Budapest_1
13303  2020-10-26          NaN        0  ...          10.70   0.0  Budapest_1
13304  2020-04-30          NaN        0  ...           8.60   0.0  Budapest_1
13305  2021-04-03          NaN        1  ...           0.00   0.0  Budapest_1
13306  2023-04-08          NaN        1  ...           0.22   0.1  Budapest_1

[13307 rows x 15 columns]

       warehouse        date  orders  ...  snow  user_activity_1  user_activity_2
0       Prague_1  2020-12-05  6895.0  ...   0.0           1722.0          32575.0
1       Prague_1  2020-12-06  6584.0  ...   0.0           1688.0          32507.0
2       Prague_1  2020-12-07  7030.0  ...   0.0           1696.0          32552.0
3       Prague_1  2020-12-08  6550.0  ...   0.0           1681.0          32423.0
4       Prague_1  2020-12-09  6910.0  ...   0.0           1704.0          32410.0
...          ...         ...     ...  ...   ...              ...              ...
7335  Budapest_1  2024-03-10  6733.0  ...   0.0           2983.0          27111.0
7336  Budapest_1  2024-03-11  6492.0  ...   0.0           2975.0          27133.0
7337  Budapest_1  2024-03-12  6661.0  ...   0.0           2974.0          27151.0
7338  Budapest_1  2024-03-13  6843.0  ...   0.0           2979.0          27180.0
7339  Budapest_1  2024-03-14  8130.0  ...   0.0           2953.0          27231.0

[7340 rows x 16 columns]

      warehouse        date  ...  winter_school_holidays  school_holidays
0      Prague_1  2024-03-16  ...                       0                0
1      Prague_1  2024-03-17  ...                       0                0
2      Prague_1  2024-03-18  ...                       0                0
3      Prague_1  2024-03-19  ...                       0                0
4      Prague_1  2024-03-20  ...                       0                0
..          ...         ...  ...                     ...              ...
392  Budapest_1  2024-05-11  ...                       0                0
393  Budapest_1  2024-05-12  ...                       0                0
394  Budapest_1  2024-05-13  ...                       0                0
395  Budapest_1  2024-05-14  ...                       0                0
396  Budapest_1  2024-05-15  ...                       0                0

[397 rows x 6 columns]

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 397    │ │ int32       │ 4     │                                                          │
│ │ Number of columns │ 6      │ │ string      │ 2     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━━━┓  │
│ ┃ column_name               ┃ NA  ┃ NA %   ┃ mean      ┃ sd       ┃ p0  ┃ p25  ┃ p50  ┃ p75  ┃ p100 ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━━━┩  │
│ │ holiday                   │   0 │      0 │   0.06801 │   0.2521 │   0 │    0 │    0 │    0 │    1 │ ▇    ▁ │  │
│ │ shops_closed              │   0 │      0 │   0.02015 │   0.1407 │   0 │    0 │    0 │    0 │    1 │   ▇    │  │
│ │ winter_school_holidays    │   0 │      0 │   0.02015 │   0.1407 │   0 │    0 │    0 │    0 │    1 │   ▇    │  │
│ │ school_holidays           │   0 │      0 │   0.07053 │   0.2564 │   0 │    0 │    0 │    0 │    1 │ ▇    ▁ │  │
│ └───────────────────────────┴─────┴────────┴───────────┴──────────┴─────┴──────┴──────┴──────┴──────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name               ┃ NA      ┃ NA %       ┃ words per row                ┃ total words              ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ warehouse                 │       0 │          0 │                            1 │                      397 │  │
│ │ date                      │       0 │          0 │                            1 │                      397 │  │
│ └───────────────────────────┴─────────┴────────────┴──────────────────────────────┴──────────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯